def line():
    a = input("Ingrese el coeficiente A: ")
    b = input("Ingrese el coeficiente B: ")
    x1 = input("Ingrese el coeficiente X1: ")
    x2 = input("Ingrese el coeficiente X2: ")
    print(f"El coeficiente A de su ecuación de la recta es: {a}")
    print(f"El coeficiente B de su ecuación de la recta es: {b}")
    print(f"El coeficiente X1 de su ecuación de la recta es: {x1}")
    print(f"El coeficiente X2 de su ecuación de la recta es: {x2}")
    print("Para la siguiente ecuación:")
    print(/t f"Y = {a}X + {b}")
    print("Dados los siguiente puntos:")
    print(/t f"P1 ({x1}, {a*x1+b})")
    print(/t f"P2 ({x2}, {a*x2+b})")
